### ISSUE TITLE
Name of the file generated by generateLicenseJson is "licenses.html"

### ISSUE THREAD

**Issue by nashcft** [cookpad/LicenseToolsPlugin#11]
## Expected

`./gradlew generateLicenseJson` generates a license JSON file named `licenses.json`

## Actual

A JSON file is generated, but its name is `licenses.html`

## Reproduced version
1.0.1

**Comment by kazyApp** [comment]
Thanks for reporting. 😄  @nashcft

**Comment by nashcft** [comment]
Thanks for the quick fix :)
