### ISSUE TITLE
Generated JSON structure is different from the one generated by license-tools-plugin

### ISSUE THREAD

**Issue by nashcft** [cookpad/LicenseToolsPlugin#12]
When I replaced `license-tools-plugin` with this plugin, I found that JSON structure was changed like following: 

license-tools-plugin
```
{
  "licenses": [
    { /* license information */ },
    ...
  ]
}
```
this plugin
```
[
    { /* license information */ },
    ...
 ]
```

I think either is fine, but I'd like to know which one is intended output for this plugin.

**Comment by kazyApp** [comment]
Thanks for trying this plugin and bug reporting. 👍 

Probably I think that the root key name is `libraries`, not `licenses`
(like that https://github.com/cookpad/license-tools-plugin/blob/174229bfa207a74565c869ed7c34b70a0f20fcab/example/src/main/assets/licenses.json)

**Comment by nashcft** [comment]
Thank you for the fix 🙏 

> Probably I think that the root key name is `libraries`, not `licenses`

You're right. I fixed description 🙇
