### ISSUE TITLE
Need change logs or release notes

### ISSUE THREAD

**Issue by chibatching** [cookpad/LicenseToolsPlugin#19]
Currently, release information is only the issue like #15 
It is too hard to find specific version info, because the issue has been closed.

We need CHANGELOG.md on root of this repository or [release page](https://github.com/cookpad/LicenseToolsPlugin/releases) to show release notes

**Comment by kazyApp** [comment]
Great suggestion! 👍 
We try to maintain `CHANGELOG.md`
