### ISSUE TITLE
Sample project should actually demonstrate use of the library

### ISSUE THREAD

**Issue by elroid** [cookpad/LicenseToolsPlugin#37]
Hi. The library is very useful, thanks! I've managed to generate the html, and I'm sure I can work out how to show it but I thought I'd see how you suggest doing it in "example/MainActivity". I have to say, I found this a bit confusing. It seems to have several screens, but none of them include the `licenses.html` file, which I thought was the point of having a sample? This seems to be little more than a demonstration of how to use NavComponent with an AppBar.

**Comment by mezpahlan** [comment]
It would be especially useful to demonstrate how to use this in a multi module gradle project as well.

**Comment by k4zy** [comment]
You were absolutely right, so I revamped the sample project. https://github.com/cookpad/LicenseToolsPlugin/pull/67
Thanks!
